# Pages placed under these sections will be shown on homepage and archive page.
mainSections:
  - posts
# Output page's full content in RSS.
rssFullContent: true
favicon: images/favicon.ico
footer:
  since: 2023
  customText: "å¹»æ¢¦çš„åšå®¢"
dateFormat:
  published: "2006-01-02"
  lastUpdated: "2006-01-02 15:04"
sidebar:
  emoji: ğŸ˜Š
  subtitle: æ´»åˆ°è€å­¦åˆ°è€
  avatar:
    enabled: true
    local: true
    src: "images/avatar.jpg"
article:
  math: true
  readingTime: true
  toc: true
  license:
    enabled: true
    default: Licensed under CC BY-NC-SA 4.0
## Widgets
widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    # - type: categories
    #   params:
    #     limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc
# opengraph:
#   twitter:
#     site: ""
#     card: summary_large_image
defaultImage:
  opengraph:
    enabled: false
    local: false
    src: ""
colorScheme:
  toggle: true
  default: auto
imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true
comments:
  enabled: true
  provider: giscus
  giscus:
    repo: "MysticalDream/PBlog"
    repoID: "R_kgDOKsZKxQ"
    category: "General"
    categoryID: "DIC_kwDOKsZKxc4Ca4oE"
    mapping: "pathname"
    strict: 1
    lightTheme: "preferred_color_scheme"
    darkTheme: "preferred_color_scheme"
    reactionsEnabled: 1
    emitMetadata: 1
    lang: "zh-CN"
